# What is Numpy?
Numpy is Python’s library to help you in linear algebra. Linear algebra is nothing but a branch
of mathematics dealing with matrices.
You might have heard about Matrices and their operations. That is exactly what linear algebra
is. Matrices are also known as arrays or lists in programming terms.
Linear algebra is critical for machine learning because of the huge amounts of data available.
To work with these large data sets, you need to leverage matrices for sure. To make the work
easy, Python has numpy for you.
Numpy is the basic package for scientific computing using Python.
Machine learning uses several libraries to do the works easily, and numpy is the most important
among them. You will be using numpy for almost all the machine learning projects.
Numpy is incredibly fast as well since it has got its bindings with C libraries.


# 1D Array

In [18]:
import numpy as np
coollist = [1,2,3,4]

In [19]:
np.array(coollist)

array([1, 2, 3, 4])

# 2D Array

In [7]:
multilist = [[1,2,3],[4,5,6],[5,6,7]]
np.array(multilist)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

# Array with in a Range

In [9]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
#fill the matrix with all zeros
np.arange(4)   

array([0, 1, 2, 3])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Converting 1D Array into 2D Array

In [3]:
import numpy as np
oneDArray = np.arange(12)
oneDArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
twoDarray = oneDArray.reshape(3,4)
twoDarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
twoDarray[1,1]       #selecting 2d element

5

In [17]:
twoDarray[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

# Indexing and Slicing an Array

In [36]:
import numpy as np
myarray = np.arange(4,11)
myarray

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
myarray[2]

6

In [38]:
sliciemyarray = myarray[0:3]
sliciemyarray

array([4, 5, 6])

In [39]:
sliciemyarray[:] = 9
sliciemyarray

array([9, 9, 9])

In [40]:
myarray

array([ 9,  9,  9,  7,  8,  9, 10])

In [41]:
copyarray = myarray.copy()
copyarray

array([ 9,  9,  9,  7,  8,  9, 10])

In [42]:
copyarray

array([ 9,  9,  9,  7,  8,  9, 10])

In [43]:
myarray

array([ 9,  9,  9,  7,  8,  9, 10])

In [44]:
myarray[myarray>8]   # conditional distribution of elements

array([ 9,  9,  9,  9, 10])

# Numpy Array Operations

In [45]:
newArray = np.arange(0,5)
newArray

array([0, 1, 2, 3, 4])

In [46]:
newArray*2

array([0, 2, 4, 6, 8])

In [47]:
newArray+3

array([3, 4, 5, 6, 7])

In [48]:
np.sqrt(newArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

# Cross Product and Dot Product

In [51]:
x = [1,2,3]
y = [4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [52]:
np.dot(x,y)

32

# Transpose of a Matrix

In [53]:
x = [[1,2],[3,4]]
np.transpose(x)

array([[1, 3],
       [2, 4]])

# Mean, Standard Deviation and Covariance

In [54]:
x = [[1,2],[3,4]]
np.mean(x)

2.5

In [55]:
np.std(x)

1.118033988749895

In [56]:
np.cov(x)

array([[0.5, 0.5],
       [0.5, 0.5]])